  
  name: CI

#Controls when the workflow will run
on: 

#Triggers the workflow on push or pull request events but for only the main branch
  push:
    branches: [main]
  pull_request: 
    branches: [main]
# Allows you to run this workflow manually from the actions tab
workflow_dispatch:

# A workflow run is made up of one or more jobs that run sequentially or in parallkel

jobs:

  build: 

    runs-on: ubuntu-latest
